# Excess mortality in US vs Europe: assemble the dataset

In [1]:
import numpy as np
import pylab as plt
import pandas as pd

## US data

In [2]:
# Ariel's analysis for this project

us = pd.read_csv('data/us_states_merged_20240217.csv')

# 2020-02-03 to 2021-07-03
# 2021-07-04 to 2022-04-02
# 2022-04-03 to 2023-04-30

window1 = ((us.year==2020) & (us.time>=6))  | ((us.year==2021) & (us.time<=26))
window2 = ((us.year==2021) & (us.time>=27)) | ((us.year==2022) & (us.time<=13))
window3 = ((us.year==2022) & (us.time>=14)) | ((us.year==2023) & (us.time<=17))

us1 = us[window1][['state', 'excess_deaths']].groupby('state').sum().reset_index()
us2 = us[window2][['state', 'excess_deaths']].groupby('state').sum().reset_index()
us3 = us[window3][['state', 'excess_deaths']].groupby('state').sum().reset_index()

us = us1

us = us.rename(columns={'state': 'region', 'excess_deaths': 'excess20_21'})
us['excess21_22'] = us2['excess_deaths']
us['excess22_23'] = us3['excess_deaths']

us.loc[us['region'] == 'DC', 'region'] = 'District of Columbia'
us = us.drop(us[us.region=='United States'].index)
us['US'] = 1

us

                  region   excess20_21  excess21_22   excess22_23  US
0                Alabama  14594.646154    10166.475   2864.582692   1
1                 Alaska    806.323077     1635.125   1088.678846   1
2                Arizona  21072.415385    14881.300   5568.069231   1
3               Arkansas   7722.338462     6601.725   2890.048077   1
4             California  77367.400000    37815.025  25478.025000   1
5               Colorado   8352.276923     7919.175   3943.421154   1
6            Connecticut   6523.200000     2475.850    474.850000   1
7   District of Columbia   1764.615385      714.800    293.969231   1
8               Delaware   2050.384615     1408.125    976.755769   1
9                Florida  40727.307692    40712.300  11304.884615   1
10               Georgia  24550.969231    19266.150   6946.411538   1
11                Hawaii     92.153846     1240.925    905.617308   1
12                 Idaho   2194.384615     3545.175   1135.005769   1
13              Illinois  25234.276923    13864.025   4564.271154   1
14               Indiana  13813.169231    11165.100   2501.761538   1
15                  Iowa   4430.492308     3604.325    951.140385   1
16                Kansas   5018.123077     4671.325   1886.878846   1
17              Kentucky   9090.076923    10091.650   4023.296154   1
18             Louisiana  13315.784615     8250.300   1674.130769   1
19                 Maine   1037.738462     2256.650   1636.173077   1
20              Maryland  10692.984615     4065.325   -538.044231   1
21         Massachusetts   9379.076923     3720.250   1369.496154   1
22              Michigan  20704.569231    14748.000   3320.461538   1
23             Minnesota   6245.523077     5564.850   2251.403846   1
24           Mississippi  10068.569231     6798.600   1728.461538   1
25              Missouri  12085.723077     9645.700   2329.853846   1
26               Montana   1884.030769     2508.625    862.563462   1
27              Nebraska   2531.523077     2208.150    956.503846   1
28                Nevada   6317.753846     6041.275   2137.967308   1
29         New Hampshire    993.246154     1309.300   1144.607692   1
30            New Jersey  23714.030769     5488.175  -1239.286538   1
31            New Mexico   5379.753846     4677.025   1614.917308   1
32              New York  57422.261538    16276.475   7904.151923   1
33        North Carolina  18890.938462    16612.375   7235.698077   1
34          North Dakota   1310.984615      840.175   -189.594231   1
35                  Ohio  21595.400000    20357.675    252.075000   1
36              Oklahoma   8616.646154     8372.000   2528.507692   1
37                Oregon   4761.676923     7236.075   5944.921154   1
38          Pennsylvania  26381.384615    17827.000   3686.430769   1
39          Rhode Island   1868.846154      834.825     58.132692   1
40        South Carolina  13860.692308    10147.050   4370.665385   1
41          South Dakota   1866.276923     1094.575     99.821154   1
42             Tennessee  16105.107692    15047.850   3618.434615   1
43                 Texas  66290.153846    45883.750  14748.242308   1
45                  Utah   2983.861538     3498.425   1581.101923   1
46               Vermont    714.553846     1018.750   1135.842308   1
47              Virginia  13534.246154    11529.325   5613.832692   1
48            Washington   5899.738462     8805.850   7227.973077   1
49         West Virginia   4028.030769     5215.025   1995.963462   1
50             Wisconsin   7547.076923     7038.000   1492.446154   1
51               Wyoming    836.553846     1090.050    341.942308   1

In [3]:
# https://www.census.gov/data/tables/time-series/demo/popest/2020s-state-total.html

# https://www2.census.gov/programs-surveys/popest/tables/2020-2023/state/totals/NST-EST2023-POP.xlsx

pop = pd.read_excel('data/NST-EST2023-POP.xlsx', skiprows=2)

pop = pop[6:-8]

pop['Geographic Area'] = [s[1:] for s in pop['Geographic Area'].values]

pop = pop[['Geographic Area', 'Unnamed: 3']] # 2021 column
pop = pop.rename(columns={'Geographic Area': 'region', 'Unnamed: 3': 'population'})

# Merge
us = pd.merge(us, pop, on='region')

In [4]:
us['rel_excess20_21'] = us.excess20_21 / us.population * 100
us['rel_excess21_22'] = us.excess21_22 / us.population * 100
us['rel_excess22_23'] = us.excess22_23 / us.population * 100

In [5]:
us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
}
    
# invert the dictionary
abbrev_to_us_state = dict(map(reversed, us_state_to_abbrev.items()))

In [6]:
# https://data.cdc.gov/Vaccinations/COVID-19-Vaccinations-in-the-United-States-Jurisdi/unsk-b7fc/data_preview

vac = pd.read_csv('data/COVID-19_Vaccinations_in_the_United_States_Jurisdiction_20240219.csv')

vac = vac[vac.Date == '10/02/2021'][['Location', 'Series_Complete_Pop_Pct']]

vac.Location = [abbrev_to_us_state[s] if s in abbrev_to_us_state else s for s in vac.Location]

vac = vac.rename(columns={'Location': 'region', 'Series_Complete_Pop_Pct': 'vacc'})

us = pd.merge(us, vac, on='region')

In [7]:
# https://www.bea.gov/data/gdp/gdp-state
# https://apps.bea.gov/regional/histdata/releases/0322gdpstate/index.cfm

gdp = pd.read_csv('data/SAGDP1__ALL_AREAS_1997_2021.csv')

gdp = gdp[gdp.Description == 'Current-dollar GDP (millions of current dollars)']

gdp = gdp[gdp.LineCode == 3]

gdp = gdp[['GeoName', '2021']]
          
gdp = gdp.rename(columns={'GeoName': 'region', '2021': 'gdp'})

us = pd.merge(us, gdp, on='region')

us.gdp = us.gdp.astype('float') / us.population * 1e6

us['gdp_ppp'] = us.gdp

In [8]:
# # PPP adjustement

# ppp = pd.read_csv('BEA rppp.csv', skiprows=3)[:-2]

# ppp = [ppp[ppp.GeoName == state]['2019'].values[0] for state in us.region]

# us.gdp /= (np.array(ppp) / 100)

In [9]:
# https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_income_inequality
# https://data.census.gov/table/ACSDT1Y2019.B19083?q=Gini&g=040XX00US51,50,11,12,53,54,10,15,16,13,19,17,18,40,41,44,45,01,42,48,04,49,05,02,46,47,08,09,06,30,33,34,31,32,37,38,35,36,39,22,23,20,21,26,27,24,25,28,29,72,55,56_010XX00US&moe=false&tp=true&tid=ACSDT1Y2019.B19083

gini = pd.read_csv("data/ACSDT1Y2019.B19083-2026-03-03T215237.csv")
gini = pd.DataFrame({"region": gini.values[2::2,0], "gini": gini.values[3::2,1] * 100})

us = pd.merge(us, gini, on="region")

In [10]:
us

,region,excess20_21,excess21_22,excess22_23,US,population,rel_excess20_21,rel_excess21_22,rel_excess22_23,vacc,gdp,gdp_ppp,gini
0,Alabama,14594.646154,10166.475,2864.582692,1,5050380.0,0.288981,0.201301,0.056720,42.7,48925.526396,48925.526396,47.41
1,Alaska,806.323077,1635.125,1088.678846,1,734923.0,0.109715,0.222489,0.148135,50.8,74797.087586,74797.087586,43.76
2,Arizona,21072.415385,14881.300,5568.069231,1,7272487.0,0.289755,0.204625,0.076563,51.2,56540.740465,56540.740465,45.91
3,Arkansas,7722.338462,6601.725,2890.048077,1,3028443.0,0.254994,0.217991,0.095430,45.8,47729.278709,47729.278709,47.5
4,California,77367.400000,37815.025,25478.025000,1,39145060.0,0.197643,0.096602,0.065086,59.1,85748.531232,85748.531232,48.66
5,Colorado,8352.276923,7919.175,3943.421154,1,5811596.0,0.143717,0.136265,0.067854,59.5,72603.360591,72603.360591,45.48
6,Connecticut,6523.200000,2475.850,474.850000,1,3603691.0,0.181014,0.068703,0.013177,68.9,82276.088599,82276.088599,50.24
7,District of Columbia,1764.615385,714.800,293.969231,1,669037.0,0.263755,0.106840,0.043939,60.3,227204.026085,227204.026085,51.15
8,Delaware,2050.384615,1408.125,976.755769,1,1004881.0,0.204043,0.140129,0.097201,57.9,80326.128168,80326.128168,45.09
9,Florida,40727.307692,40712.300,11304.884615,1,21830708.0,0.186560,0.186491,0.051784,57.4,56173.052198,56173.052198,48.08
10,Georgia,24550.969231,19266.150,6946.411538,1,10790385.0,0.227526,0.178549,0.064376,45.7,63325.089883,63325.089883,47.95
11,Hawaii,92.153846,1240.925,905.617308,1,1446745.0,0.006370,0.085774,0.062597,58.1,62249.670813,62249.670813,43.97
12,Idaho,2194.384615,3545.175,1135.005769,1,1904537.0,0.115219,0.186144,0.059595,41.8,49522.167330,49522.167330,43.37
13,Illinois,25234.276923,13864.025,4564.271154,1,12690341.0,0.198846,0.109249,0.035966,53.6,73941.850735,73941.850735,48.0
14,Indiana,13813.169231,11165.100,2501.761538,1,6813798.0,0.202723,0.163860,0.036716,48.5,61689.413158,61689.413158,45.84
15,Iowa,4430.492308,3604.325,951.140385,1,3197944.0,0.138542,0.112708,0.029742,54.1,68744.699720,68744.699720,44.22
16,Kansas,5018.123077,4671.325,1886.878846,1,2937946.0,0.170804,0.159000,0.064224,51.3,65455.117283,65455.117283,45.0
17,Kentucky,9090.076923,10091.650,4023.296154,1,4507600.0,0.201661,0.223881,0.089256,52.7,52022.850297,52022.850297,47.64
18,Louisiana,13315.784615,8250.300,1674.130769,1,4627047.0,0.287781,0.178306,0.036181,45.6,55177.005982,55177.005982,49.78
19,Maine,1037.738462,2256.650,1636.173077,1,1378787.0,0.075265,0.163669,0.118668,68.7,55162.399994,55162.399994,44.9
20,Maryland,10692.984615,4065.325,-538.044231,1,6175045.0,0.173164,0.065835,-0.008713,64.3,70968.697394,70968.697394,45.58
21,Massachusetts,9379.076923,3720.250,1369.496154,1,6991951.0,0.134141,0.053208,0.019587,68.0,91035.291866,91035.291866,48.03
22,Michigan,20704.569231,14748.000,3320.461538,1,10038117.0,0.206259,0.146920,0.033079,52.5,56625.480655,56625.480655,46.34
23,Minnesota,6245.523077,5564.850,2251.403846,1,5717968.0,0.109226,0.097322,0.039374,58.3,72053.708590,72053.708590,44.34
24,Mississippi,10068.569231,6798.600,1728.461538,1,2949582.0,0.341356,0.230494,0.058600,43.6,42416.179649,42416.179649,48.96
25,Missouri,12085.723077,9645.700,2329.853846,1,6170393.0,0.195866,0.156322,0.037759,48.0,58335.344280,58335.344280,46.33
26,Montana,1884.030769,2508.625,862.563462,1,1106366.0,0.170290,0.226745,0.077964,48.6,53601.430268,53601.430268,45.97
27,Nebraska,2531.523077,2208.150,956.503846,1,1964253.0,0.128880,0.112417,0.048696,54.7,76562.286019,76562.286019,44.0
28,Nevada,6317.753846,6041.275,2137.967308,1,3146632.0,0.200778,0.191992,0.067945,50.8,61323.917128,61323.917128,47.1
29,New Hampshire,993.246154,1309.300,1144.607692,1,1387494.0,0.071586,0.094364,0.082495,61.6,70805.207086,70805.207086,44.06
30,New Jersey,23714.030769,5488.175,-1239.286538,1,9269175.0,0.255838,0.059209,-0.013370,64.4,72508.006376,72508.006376,47.82
31,New Mexico,5379.753846,4677.025,1614.917308,1,2116950.0,0.254128,0.220932,0.076285,63.4,51455.159546,51455.159546,47.68
32,New York,57422.261538,16276.475,7904.151923,1,19854526.0,0.289215,0.081979,0.039810,63.9,93375.480231,93375.480231,51.49
33,North Carolina,18890.938462,16612.375,7235.698077,1,10567100.0,0.178771,0.157208,0.068474,50.0,61983.486482,61983.486482,47.43
34,North Dakota,1310.984615,840.175,-189.594231,1,777982.0,0.168511,0.107994,-0.024370,44.4,81475.921037,81475.921037,45.58
35,Ohio,21595.400000,20357.675,252.075000,1,11765227.0,0.183553,0.173033,0.002143,50.3,62595.460334,62595.460334,46.51
36,Oklahoma,8616.646154,8372.000,2528.507692,1,3991634.0,0.215868,0.209739,0.063345,47.8,51795.956242,51795.956242,47.39
37,Oregon,4761.676923,7236.075,5944.921154,1,4256465.0,0.111869,0.170002,0.139668,60.9,62714.740988,62714.740988,45.0
38,Pennsylvania,26381.384615,17827.000,3686.430769,1,13013614.0,0.202721,0.136987,0.028327,58.0,64504.487378,64504.487378,47.45
39,Rhode Island,1868.846154,834.825,58.132692,1,1097092.0,0.170345,0.076094,0.005299,68.4,60103.619387,60103.619387,46.28
40,South Carolina,13860.692308,10147.050,4370.665385,1,5193848.0,0.266867,0.195367,0.084151,47.4,51999.788981,51999.788981,47.47
41,South Dakota,1866.276923,1094.575,99.821154,1,896299.0,0.208220,0.122122,0.011137,51.8,68286.922110,68286.922110,43.6
42,Tennessee,16105.107692,15047.850,3618.434615,1,6963709.0,0.231272,0.216090,0.051961,45.6,60067.731147,60067.731147,47.49
43,Texas,66290.153846,45883.750,14748.242308,1,29561286.0,0.224247,0.155216,0.049890,51.3,67159.409100,67159.409100,47.53
44,Utah,2983.861538,3498.425,1581.101923,1,3339284.0,0.089356,0.104766,0.047349,50.9,65984.803928,65984.803928,42.68
45,Vermont,714.553846,1018.750,1135.842308,1,647093.0,0.110425,0.157435,0.175530,69.6,55896.293114,55896.293114,44.71
46,Virginia,13534.246154,11529.325,5613.832692,1,8657348.0,0.156332,0.133174,0.064845,60.7,68364.007084,68364.007084,46.9
47,Washington,5899.738462,8805.850,7227.973077,1,7741433.0,0.076210,0.113750,0.093367,61.0,86234.266963,86234.266963,45.77
48,West Virginia,4028.030769,5215.025,1995.963462,1,1785249.0,0.225629,0.292118,0.111803,40.5,48953.675370,48953.675370,46.44
49,Wisconsin,7547.076923,7038.000,1492.446154,1,5879978.0,0.128352,0.119694,0.025382,56.6,62233.447132,62233.447132,43.91
50,Wyoming,836.553846,1090.050,341.942308,1,579548.0,0.144346,0.188086,0.059002,41.6,71818.727698,71818.727698,43.45

## EU data

In [11]:
# https://raw.githubusercontent.com/dkobak/excess-mortality/main/excess-mortality-timeseries.csv
    
eu = pd.read_csv('data/excess-mortality-timeseries.csv')

eu_countries = [
    'Albania',
    'Austria',
    'Belgium',
    'Bosnia',
    'Bulgaria',
    'Croatia',
    'Cyprus',
    'Czechia',
    'Denmark',
    'Estonia',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Hungary',
    'Iceland',
    'Ireland',
    'Italy',
    'Kosovo',
    'Latvia',
    'Lithuania',
    'Luxembourg',
    'Malta',
    'Moldova',
    'Montenegro',
    'Netherlands',
    'North Macedonia',
    'Norway',
    'Poland',
    'Portugal',
    'Romania',
    'Russia',
    'Serbia',
    'Slovakia',
    'Slovenia',
    'Spain',
    'Sweden',
    'Switzerland',
    'Ukraine',
    'United Kingdom'
]

# # 2020-02-03 to 2021-07-03
# # 2021-07-04 to 2022-04-02
# # 2022-04-03 to 2023-04-30

window = ((eu.year==2020) & (eu.time>=6)) | ((eu.year==2021) & (eu.time<=26))
selection = eu.country_name.isin(eu_countries) & (eu.time_unit=='weekly') & window

window = ((eu.year==2020) & (eu.time>=2)) | ((eu.year==2021) & (eu.time<=6))
selection |= eu.country_name.isin(eu_countries) & (eu.time_unit=='monthly') & window

eu1 = eu[selection][['country_name', 'excess deaths']].groupby('country_name').sum().reset_index()

window = ((eu.year==2021) & (eu.time>=27)) | ((eu.year==2022) & (eu.time<=13))
selection = eu.country_name.isin(eu_countries) & (eu.time_unit=='weekly') & window

window = ((eu.year==2021) & (eu.time>=7)) | ((eu.year==2022) & (eu.time<=3))
selection |= eu.country_name.isin(eu_countries) & (eu.time_unit=='monthly') & window

eu2 = eu[selection][['country_name', 'excess deaths']].groupby('country_name').sum().reset_index()

window = ((eu.year==2022) & (eu.time>=14)) | ((eu.year==2023) & (eu.time<=17))
selection = eu.country_name.isin(eu_countries) & (eu.time_unit=='weekly') & window

window = ((eu.year==2022) & (eu.time>=4)) | ((eu.year==2023) & (eu.time<=4))
selection |= eu.country_name.isin(eu_countries) & (eu.time_unit=='monthly') & window

eu3 = eu[selection][['country_name', 'excess deaths']].groupby('country_name').sum().reset_index()

eu = eu1.rename(columns={'country_name': 'region', 'excess deaths': 'excess20_21'})

eu['excess21_22'] = eu2['excess deaths']
eu.loc[eu.region != 'Ukraine', 'excess22_23'] = eu3['excess deaths'].values

eu['US'] = 0

eu

             region  excess20_21  excess21_22  excess22_23  US
0           Albania      11028.2       5476.3      -1207.9   0
1           Austria       9233.6       6350.2       9345.4   0
2           Belgium      16729.4       4145.4       7192.5   0
3            Bosnia      13698.8       9034.5        134.1   0
4          Bulgaria      32740.0      35437.0      -1711.4   0
5           Croatia       9921.4      10419.4       2983.8   0
6            Cyprus        443.8       1208.9        322.8   0
7           Czechia      34085.4       8384.1       3308.2   0
8           Denmark      -1289.2       3107.9       2675.8   0
9           Estonia       1644.4       1954.8        922.2   0
10          Finland        549.0       4569.8       6662.4   0
11           France      67652.6      21593.3      31813.5   0
12          Germany      45832.6      46692.0     111887.3   0
13           Greece      10582.8      19907.4       8141.5   0
14          Hungary      25276.6      13229.1       2872.9   0
15          Iceland         -6.4        211.1        263.9   0
16          Ireland       2675.6       1841.2       4016.6   0
17            Italy     147136.2      41596.3      59365.1   0
18           Kosovo       4987.0       1343.5      -1532.1   0
19           Latvia       3350.4       5038.9       1546.2   0
20        Lithuania      10238.4       8640.6       4814.4   0
21       Luxembourg        104.6        -83.1       -252.1   0
22            Malta        373.8        272.7         49.5   0
23          Moldova      10491.7       7165.1        838.9   0
24       Montenegro       1918.2       1651.8       -301.5   0
25      Netherlands      18187.4      11370.9      15857.9   0
26  North Macedonia       9916.9       6275.4        256.0   0
27           Norway      -1139.2       3282.6       4771.4   0
28           Poland     115807.0      57176.1      -1534.9   0
29         Portugal      17526.2       3361.8       9432.6   0
30          Romania      58792.8      60217.9     -10918.7   0
31           Russia     578133.5     627442.0      76962.8   0
32           Serbia      29343.3      29162.6        622.4   0
33         Slovakia      17009.8       9908.8       3035.3   0
34         Slovenia       3911.6       1594.7        424.8   0
35            Spain      81017.8      20516.3      41285.0   0
36           Sweden       8592.4       2393.4       4918.7   0
37      Switzerland       8969.2       3997.0       5652.7   0
38          Ukraine      93526.2      89397.0          NaN   0
39   United Kingdom     103672.2      30814.0      73272.9   0

In [12]:
# https://population.un.org/wpp/

# https://population.un.org/wpp/Download/Files/1_Indicators%20(Standard)/CSV_FILES/WPP2022_TotalPopulationBySex.zip
    
pop = pd.read_csv('data/WPP2022_TotalPopulationBySex.zip', low_memory=False)
pop = pop[(pop['Variant'] == 'Medium') & (pop['Time'] == 2021)]
pop = pop[['Location', 'PopTotal']]
pop = pop.rename(columns={'Location': 'region', 'PopTotal': 'population'})
pop['population'] *= 1000

# Rosstat, estimate for 1 Jan 2021    
pop = pd.concat(
    [pop, pd.DataFrame({'region': ['Russia'], 'population': [146_171_015]})],
    ignore_index=True
)
# pop = pop.append({'region': 'Russia', 'population': 146_171_015}, ignore_index=True)

# Ukrstat 2021, according to Wikipedia (this does not include Crimea) 
# Donetsk People's Republic population, according to Wikipedia
# Luhansk People's Republic population, according to Wikipedia
pop.loc[pop.region=='Ukraine', 'population'] = 41_167_336 - 2_300_000 - 1_500_000

# World Bank dataset
pop = pd.concat(
    [pop, pd.DataFrame({'region': ['Kosovo'], 'population': [1_700_000]})],
    ignore_index=True
)
# pop = pop.append({'region': 'Kosovo', 'population': 1_700_000}, ignore_index=True)
pop.loc[pop.region == 'Serbia', 'population'] -= 1_700_000

# Name shortening
pop.loc[pop.region=='Bosnia and Herzegovina', 'region'] = 'Bosnia'
pop.loc[pop.region=='Republic of Moldova', 'region'] = 'Moldova'

pop = pop[pop.region.isin(eu_countries)]

# Merge
eu = pd.merge(eu, pop, on='region')

In [13]:
eu['rel_excess20_21'] = eu.excess20_21 / eu.population * 100
eu['rel_excess21_22'] = eu.excess21_22 / eu.population * 100
eu['rel_excess22_23'] = eu.excess22_23 / eu.population * 100

In [14]:
# https://data.worldbank.org/indicator/NY.GDP.PCAP.CD

gdp = pd.read_csv('data/API_NY.GDP.PCAP.CD_DS2_en_csv_v2_184.csv', skiprows=4)

gdp.loc[gdp['Country Name']=='Bosnia and Herzegovina', 'Country Name'] = 'Bosnia'
gdp.loc[gdp['Country Name']=='Russian Federation', 'Country Name'] = 'Russia'
gdp.loc[gdp['Country Name']=='Slovak Republic', 'Country Name'] = 'Slovakia'

gdp = gdp[gdp['Country Name'].isin(eu_countries)][['Country Name', '2021']]
gdp = gdp.rename(columns={'Country Name': 'region', '2021': 'gdp'})

eu = pd.merge(eu, gdp, on='region')

In [15]:
# https://data.worldbank.org/indicator/NY.GDP.PCAP.PP.CD

gdp = pd.read_csv('data/API_NY.GDP.PCAP.PP.CD_DS2_en_csv_v2_9.csv', skiprows=4)

gdp.loc[gdp['Country Name']=='Bosnia and Herzegovina', 'Country Name'] = 'Bosnia'
gdp.loc[gdp['Country Name']=='Russian Federation', 'Country Name'] = 'Russia'
gdp.loc[gdp['Country Name']=='Slovak Republic', 'Country Name'] = 'Slovakia'

gdp = gdp[gdp['Country Name'].isin(eu_countries)][['Country Name', '2021']]
gdp = gdp.rename(columns={'Country Name': 'region', '2021': 'gdp_ppp'})

eu = pd.merge(eu, gdp, on='region')

In [16]:
# https://covid.ourworldindata.org/data/owid-covid-data.csv

vac = pd.read_csv('data/owid-covid-data.zip', low_memory=False)

vac.loc[vac.location=='Bosnia and Herzegovina', 'location'] = 'Bosnia'

vac = vac[(vac.date >= '2021-10-02') & (vac.location.isin(eu_countries))]

v1 = vac[['location', 'people_fully_vaccinated_per_hundred']].groupby('location').min().reset_index()
v2 = vac[['location', 'people_vaccinated_per_hundred']].groupby('location').min().reset_index()

v1.loc[v1.location=='Switzerland', 'people_fully_vaccinated_per_hundred'] = \
    v2[v2.location=='Switzerland']['people_vaccinated_per_hundred']

vac = v1.rename(columns={'location': 'region', 'people_fully_vaccinated_per_hundred': 'vacc'})

eu = pd.merge(eu, vac, on='region')

In [17]:
# https://data.worldbank.org/indicator/SI.POV.GINI

gini = pd.read_csv("data/API_SI.POV.GINI_DS2_en_csv_v2_47.csv", skiprows=4)
gini["gini"] = np.nanmax(gini.values[:,4:-1].astype(float), axis=1)
gini = gini.rename(columns={"Country Name": "region"})
gini = gini[["region", "gini"]]

eu = pd.merge(eu, gini, on="region")

/tmp/ipykernel_1368836/3279447760.py:4: RuntimeWarning: All-NaN slice encountered
  gini["gini"] = np.nanmax(gini.values[:,4:-1].astype(float), axis=1)

In [18]:
eu

,region,excess20_21,excess21_22,excess22_23,US,population,rel_excess20_21,rel_excess21_22,rel_excess22_23,gdp,gdp_ppp,vacc,gini
0,Albania,11028.2,5476.3,-1207.9,0,2854710.0,0.386316,0.191834,-0.042313,6377.203096,15471.056173,28.34,34.6
1,Austria,9233.6,6350.2,9345.4,0,8922082.0,0.103492,0.071174,0.104745,53517.890451,59828.882812,62.34,31.5
2,Belgium,16729.4,4145.4,7192.5,0,11611419.0,0.144077,0.035701,0.061943,51850.397184,59508.673870,72.87,33.1
3,Bulgaria,32740.0,35437.0,-1711.4,0,6885868.0,0.475467,0.514634,-0.024854,12219.341871,27975.174303,19.71,41.3
4,Croatia,9921.4,10419.4,2983.8,0,4060135.0,0.244361,0.256627,0.073490,17809.032390,35155.627182,40.54,33.7
5,Cyprus,443.8,1208.9,322.8,0,1244188.0,0.035670,0.097164,0.025945,32745.843750,46110.097656,62.15,37.0
6,Czechia,34085.4,8384.1,3308.2,0,10510751.0,0.324291,0.079767,0.031474,26822.514186,45630.037807,57.11,27.5
7,Denmark,-1289.2,3107.9,2675.8,0,5854240.0,-0.022022,0.053088,0.045707,69268.651798,66086.879455,72.71,29.9
8,Estonia,1644.4,1954.8,922.2,0,1328701.0,0.123760,0.147121,0.069406,27943.701220,43476.854226,54.95,39.4
9,Finland,549.0,4569.8,6662.4,0,5535992.0,0.009917,0.082547,0.120347,53504.693648,54778.269006,63.64,28.3
10,France,67652.6,21593.3,31813.5,0,64531444.0,0.104837,0.033462,0.049299,43671.308410,51378.225657,66.05,37.1
11,Germany,45832.6,46692.0,111887.3,0,83408554.0,0.054950,0.055980,0.134144,51426.750365,59055.241460,64.35,32.4
12,Greece,10582.8,19907.4,8141.5,0,10445365.0,0.101316,0.190586,0.077944,20310.682480,31477.812084,59.31,37.0
13,Hungary,25276.6,13229.1,2872.9,0,9709786.0,0.260321,0.136245,0.029588,18753.046945,36735.909895,56.80,34.7
14,Iceland,-6.4,211.1,263.9,0,370335.0,-0.001728,0.057002,0.071260,68710.244201,58293.978147,74.34,31.8
15,Ireland,2675.6,1841.2,4016.6,0,4986526.0,0.053657,0.036924,0.080549,102001.798249,108516.987583,74.62,37.0
16,Italy,147136.2,41596.3,59365.1,0,59240329.0,0.248372,0.070216,0.100211,36449.258338,47591.861957,69.78,36.7
17,Kosovo,4987.0,1343.5,-1532.1,0,1700000.0,0.293353,0.079029,-0.090124,5269.783901,13113.697547,30.95,57.4
18,Latvia,3350.4,5038.9,1546.2,0,1873919.0,0.178791,0.268896,0.082512,20930.398237,34769.638451,46.73,39.0
19,Lithuania,10238.4,8640.6,4814.4,0,2786651.0,0.367409,0.310071,0.172767,23849.615699,44049.969064,60.09,38.4
20,Luxembourg,104.6,-83.1,-252.1,0,639321.0,0.016361,-0.012998,-0.039432,133711.794436,131630.774358,71.45,35.4
21,Malta,373.8,272.7,49.5,0,526748.0,0.070964,0.051770,0.009397,34881.291273,50788.541372,79.40,34.6
22,Moldova,10491.7,7165.1,838.9,0,3061506.0,0.342697,0.234038,0.027402,5274.744847,15121.724329,24.14,42.6
23,Montenegro,1918.2,1651.8,-301.5,0,627859.0,0.305514,0.263085,-0.048020,9465.961530,23318.143022,34.19,41.2
24,Netherlands,18187.4,11370.9,15857.9,0,17501696.0,0.103918,0.064970,0.090608,58727.870547,64488.820694,62.82,31.1
25,North Macedonia,9916.9,6275.4,256.0,0,2103330.0,0.471486,0.298355,0.012171,6778.562878,18934.022984,35.25,46.1
26,Norway,-1139.2,3282.6,4771.4,0,5403021.0,-0.021085,0.060755,0.088310,93072.892512,81866.795185,67.75,31.6
27,Poland,115807.0,57176.1,-1534.9,0,38307726.0,0.302307,0.149255,-0.004007,18050.279444,38241.711866,48.93,38.0
28,Portugal,17526.2,3361.8,9432.6,0,10290103.0,0.170321,0.032670,0.091667,24661.166487,36731.397643,80.89,38.9
29,Romania,58792.8,60217.9,-10918.7,0,19328560.0,0.304176,0.311549,-0.056490,14946.624969,36122.761787,27.53,39.6
30,Serbia,29343.3,29162.6,622.4,0,5596769.0,0.524290,0.521061,0.011121,9232.961606,21476.531747,42.35,40.5
31,Slovenia,3911.6,1594.7,424.8,0,2119410.0,0.184561,0.075243,0.020043,29331.064701,44033.763727,48.99,30.9
32,Spain,81017.8,20516.3,41285.0,0,47486935.0,0.170611,0.043204,0.086940,30488.820953,41182.459621,77.26,36.5
33,Sweden,8592.4,2393.4,4918.7,0,10467097.0,0.082090,0.022866,0.046992,61417.680877,60396.713701,62.24,31.6
34,Switzerland,8969.2,3997.0,5652.7,0,8691406.0,0.103196,0.045988,0.065038,93446.434452,77181.375348,63.77,36.0
35,Ukraine,93526.2,89397.0,NaN,0,37367336.0,0.250289,0.239238,NaN,4827.845703,14289.040039,14.55,39.2
36,United Kingdom,103672.2,30814.0,73272.9,0,67281039.0,0.154088,0.045799,0.108906,46869.759058,50361.273756,66.61,38.8

## Concatenate

In [19]:
df = pd.concat((us, eu))

In [20]:
df

,region,excess20_21,excess21_22,excess22_23,US,population,rel_excess20_21,rel_excess21_22,rel_excess22_23,vacc,gdp,gdp_ppp,gini
0,Alabama,14594.646154,10166.475,2864.582692,1,5050380.0,0.288981,0.201301,0.056720,42.70,48925.526396,48925.526396,47.41
1,Alaska,806.323077,1635.125,1088.678846,1,734923.0,0.109715,0.222489,0.148135,50.80,74797.087586,74797.087586,43.76
2,Arizona,21072.415385,14881.300,5568.069231,1,7272487.0,0.289755,0.204625,0.076563,51.20,56540.740465,56540.740465,45.91
3,Arkansas,7722.338462,6601.725,2890.048077,1,3028443.0,0.254994,0.217991,0.095430,45.80,47729.278709,47729.278709,47.5
4,California,77367.400000,37815.025,25478.025000,1,39145060.0,0.197643,0.096602,0.065086,59.10,85748.531232,85748.531232,48.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,Spain,81017.800000,20516.300,41285.000000,0,47486935.0,0.170611,0.043204,0.086940,77.26,30488.820953,41182.459621,36.5
33,Sweden,8592.400000,2393.400,4918.700000,0,10467097.0,0.082090,0.022866,0.046992,62.24,61417.680877,60396.713701,31.6
34,Switzerland,8969.200000,3997.000,5652.700000,0,8691406.0,0.103196,0.045988,0.065038,63.77,93446.434452,77181.375348,36.0
35,Ukraine,93526.200000,89397.000,NaN,0,37367336.0,0.250289,0.239238,NaN,14.55,4827.845703,14289.040039,39.2
36,United Kingdom,103672.200000,30814.000,73272.900000,0,67281039.0,0.154088,0.045799,0.108906,66.61,46869.759058,50361.273756,38.8

In [21]:
df.to_csv('us-vs-eu-data.csv', index=False, float_format='%.3f')